name: flutter_bloc_toolbox
description: Build on top of the wonderful flutter_bloc package. Contains some useful blocs/cubits.
version: 0.0.2
homepage: https://github.com/VincentDR/flutter_bloc_toolbox
issue_tracker: https://github.com/VincentDR/flutter_bloc_toolbox/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  rxdart: ^0.27.7

dev_dependencies:
  analysis_options: any
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:

