name: flutter_bloc_toolbox
description: Build on top of the wonderful flutter_bloc package. Contains some useful blocs/cubits.
version: 0.1.11
homepage: https://github.com/VincentDR/flutter_bloc_toolbox
repository: https://github.com/VincentDR/flutter_bloc_toolbox
issue_tracker: https://github.com/VincentDR/flutter_bloc_toolbox/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc_test: ^9.1.7
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  meta: ^1.15.0

dev_dependencies:
  analysis_options: any
  data_fixture_dart: ^2.2.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:

