name: Publish to pub.dev
on: [push]
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          # Specify the github actions deployment environment
          environment: pub.dev
#      - uses: dart-lang/setup-dart@v1
#      - name: Install dependencies
#        run: dart pub get
#      - name: Publish
#        with:
#          # Specify the github actions deployment environment
#          environment: pub.dev
#        run: dart pub publish --force