name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: self-hosted
#    with:
#      # Specify the github actions deployment environment
#      environment: pub.dev
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Format
        run: dart format ./lib -l 80 && dart fix --apply
      - name: Publish
        run: dart pub publish --force