name: Run tests and upload coverage reports to Codecov
on: [push]
with:
  environment: pub.dev
jobs:
  job_tests:
    name: Run tests
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Flutter test
        run: |
          pwd
          flutter pub get
          flutter analyze
          flutter test --coverage
  job_export:
    name: Export Codecov reports
    needs: job_tests
    runs-on: self-hosted
    steps:
      - name: Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}